config/routes.rb
Rails.application.routes.draw do
  root 'workouts#index'
  devise_for :users

  resources :workouts do
    resources :days, except: %i[index] do
      resources :exercises, except: %i[index show] do
        resources :exercise_sets, except: %i[index show]
      end
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
  end

  resources :workouts do
    resources :days, except: %i[index] do
      resources :history_days do
        resources :history_exercises do
          resources :history_sets
        end
      end
    end
  end

  resources :history_days do
    resources :history_exercises do
      resources :history_sets
    end
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  validates :name, presence: true

  # scope :ordered, -> { order(id: :desc) }

  # after_create_commit -> { broadcast_prepend_later_to "workouts" }
  # after_update_commit -> { broadcast_replace_later_to "workouts" }
  # after_destroy_commit -> { broadcast_remove_to "workouts" }
  # Those three callbacks are equivalent to the following single line
  belongs_to :user
  has_many :days, dependent: :destroy
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @workouts = current_user.workouts.order(:created_at)
  end

  def show
    @days = @workout.days.order(:created_at)
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = current_user.workouts.build(workout_params)

    if @workout.save
      respond_to do |format|
        format.html { redirect_to workouts_path, notice: 'Quote was successfully created.' }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @workout.update(workout_params)
      respond_to do |format|
        format.html { redirect_to workouts_path, notice: 'Workout was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Workout was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_path, notice: 'Workout was successfully destroyed.' }
      format.turbo_stream
    end
  end

  private

  def set_workout
    @workout = current_user.workouts.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:name)
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |f| %>
  <div class="border shadow-md mb-3 py-3 px-5 rounded-lg w-full">
    <% if workout.errors.any? %>
      <div class="bg-red-100 rounded-md mb-3 py-2 text-red-700 px-3">
        <i class="fa-solid fa-triangle-exclamation text-red-700 pr-1"></i>
        <%= workout.errors.full_messages.to_sentence.capitalize %>
      </div>
    <% end %>
    <div class="flex gap-4">
      <div class="flex-grow">
        <%= f.text_field :name, autofocus: true, placeholder: 'Name of your workout',
        id: 'Name', class: "border border-gray-300 rounded-md h-12 w-full focus:border-blue-300 focus:ring-gray-100 p-3" %>
      </div>
      <div>
        <%= link_to workouts_path do %>
          <i class="fa-solid fa-arrow-rotate-left fa-xl bg-gray-200 rounded-md p-3 hover:bg-gray-300"></i>
        <% end %>
      </div>
      <div>
        
          <%= button_tag type: 'submit', id: 'submit' do %>
            <i class="fa-solid fa-check text-white bg-green-600 p-3 fa-xl rounded-md hover:bg-green-500"></i>
          <% end %>
        
      </div>
    </div>
  </div>
<% end %>

app/views/workouts/_workout.html.erb
<%= turbo_frame_tag workout do %>
  <div class="flex justify-between border shadow-md mb-4 py-3 px-5 items-center rounded-lg">
    <div id="workout_name">
      <%= link_to workout.name, workout_path(workout), data: { turbo_frame: "_top" }, class: "text-red-700 text-lg font-medium hover:text-red-600" %>
    </div>
    <div class="flex gap-2">
      <%= button_to workout_path(workout), id: "destroy_workout", method: :delete,  data: { turbo_confirm: "Are you sure?" }, class: "bg-gray-200 py-2 px-3 rounded-md hover:bg-gray-300" do %>
        <i class="fa-regular fa-trash-can fa-xl"></i>
      <% end %>
      <%= link_to edit_workout_path(workout), id: 'Edit', class: "bg-gray-200 py-2 px-3 rounded-md hover:bg-gray-300" do %>
        <i class="fa-regular fa-pen-to-square fa-xl"></i>
      <% end %>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/workouts/create.turbo_stream.erb
<%= turbo_stream.update Workout.new, "" %>

<%= turbo_stream.append "workouts", @workout %>

app/views/workouts/create_turbo_stream.erb
<%= turbo_stream.append "workouts", @workout %>

<%= turbo_stream.update Workout.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/workouts/destroy.turbo_stream.erb
<%= turbo_stream.remove @workout %>

app/views/workouts/edit.html.erb
  <%= link_to sanitize("&larr; Back to workout"), workout_path(@workout) %>
<h1>Edit workout</h1>

<%= turbo_frame_tag @workout do %>
  <%= render "form", workout: @workout %>
<% end %>

app/views/workouts/index.html.erb
<div class="flex flex-wrap items-center justify-between my-6 gap-2 max-[320px]:justify-evenly">
  <h1 class="text-4xl font-bold">Workouts</h1>
  <%= link_to "New workout",
                  new_workout_path,
                  data: { turbo_frame: dom_id(Workout.new) },
                  class: "bg-red-700 hover:bg-red-600 text-white text-lg font-semibold py-3 px-5 rounded-md" %>
</div>
<%= turbo_frame_tag Workout.new %>
<%= turbo_frame_tag "workouts" do %>
  <%= render @workouts %>
<% end %>

app/views/workouts/new.html.erb
  <%= link_to sanitize("&larr; Back to workouts"), workouts_path %>
<h1>New workout</h1>
<%= turbo_frame_tag @workout do %>
  <%= render "form", workout: @workout %>
<% end %>

app/views/workouts/show.html.erb
<%= link_to sanitize("&larr; Back to workouts"), workouts_path, class: "text-red-700 text-lg hover:text-red-600 mt-2" %>
<div class="flex justify-between my-4 py-3 items-center">
  <h1 class="text-4xl font-bold">
    <%= @workout.name %>
  </h1>
  <%= link_to "Add Day", new_workout_day_path(@workout),
                data: { turbo_frame: dom_id(Day.new) },
                class: "bg-red-700 hover:bg-red-600 text-white text-lg font-semibold py-3 px-5 rounded-md" %>
</div>
<%= turbo_frame_tag Day.new %>
<%= turbo_frame_tag "days" do %>
  <%= render @days, workout: @workout %>
<% end %>

app/views/workouts/update.turbo_stream.erb
<%= turbo_stream.replace @workout %>