config/routes.rb
Rails.application.routes.draw do
  root 'workouts#index'
  devise_for :users

  resources :workouts do
    resources :days, except: %i[index] do
      resources :exercises, except: %i[index show] do
        resources :exercise_sets, except: %i[index show]
      end
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
  end

  resources :workouts do
    resources :days, except: %i[index] do
      resources :history_days do
        resources :history_exercises do
          resources :history_sets
        end
      end
    end
  end

  resources :history_days do
    resources :history_exercises do
      resources :history_sets
    end
  end
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :exercises, dependent: :destroy
  has_many :history_days
  belongs_to :workout
  validates :title, presence: true
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_workout
  before_action :set_day, only: %i[edit update destroy show]

  def new
    @day = @workout.days.build
  end

  def show
    @exercises = @day.exercises.includes(:exercise_sets).order(:created_at)
  end

  def create
    @day = @workout.days.build(day_params)

    if @day.save
      respond_to do |format|
        format.html { redirect_to workout_path(@workout), notice: 'Day was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Day was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @day.update(day_params)
      respond_to do |format|
        format.html { redirect_to workout_path(@workout), notice: 'Day was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Day was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @day.destroy

    respond_to do |format|
      format.html { redirect_to workout_path(@workout), notice: 'Day was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'Day was successfully destroyed.' }
    end
  end

  private

  def set_day
    @day = @workout.days.find(params[:id])
  end

  def day_params
    params.require(:day).permit(:title)
  end

  def set_workout
    @workout = current_user.workouts.find(params[:workout_id])
  end
end

app/views/days/_day.html.erb
<%= turbo_frame_tag day do %>
  <div class="flex justify-between border shadow-md mb-4 py-3 px-5 items-center rounded-lg">
    <h1 class="text-red-700 text-lg font-medium hover:text-red-600"><%= link_to day.title, workout_day_path(workout, day), data: { turbo_frame: "_top" } %></h1>
    <div class="flex gap-2">
      <%= button_to [workout, day], method: :delete,  data: { turbo_confirm: "Are you sure?" }, id: 'delete_day', class: "bg-gray-200 py-2 px-3 rounded-md hover:bg-gray-300" do %>
        <i class="fa-regular fa-trash-can fa-xl"></i>
      <% end %>
      <%= link_to [:edit, workout, day], id: 'edit_day', class: "bg-gray-200 py-2 px-3 rounded-md hover:bg-gray-300" do %>
        <i class="fa-regular fa-pen-to-square fa-xl"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/days/_form.html.erb
<%= turbo_frame_tag @day do %>
  <div class="border shadow-md mb-3 py-3 px-5 rounded-lg w-full">
    <%= form_with(model: [@workout, @day]) do |f| %>
      <% if @day.errors.any? %>
        <div class="error-message">
          <%= @day.errors.full_messages.to_sentence.capitalize %>
        </div>
      <% end %>
      <div class="flex gap-4">
        <div class="flex-grow">
          <%= f.text_field :title, autofocus: true, placeholder: 'Name of your day',
        id: 'day_title', class: "border border-gray-300 rounded-md h-12 w-full focus:border-blue-300 focus:ring-gray-100 focus:border-2 p-3" %>
        </div>
        <div>
          <%= link_to @workout do %>
            <i class="fa-solid fa-arrow-rotate-left fa-xl bg-gray-200 rounded-md p-3 hover:bg-gray-300"></i>
          <% end %>
        </div>
        <div>
          <%= button_tag type: 'submit', id: 'submit_day_title' do %>
            <i class="fa-solid fa-check text-white bg-green-600 p-3 fa-xl rounded-md hover:bg-green-500"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/days/create.turbo_stream.erb
<%# Step 1: remove the form from the Quotes#index page %>
<%= turbo_stream.update Day.new, "" %>

  <%= turbo_stream.append "days" do %>
    <%= render @day, workout: @workout %>
  <% end %>

app/views/days/destroy.turbo_stream.erb
<%= turbo_stream.remove @day %>
<%# <%= render_turbo_stream_flash_messages %> 

app/views/days/edit.html.erb
<%= link_to sanitize("&larr; Back to workout"), workout_path(@workout) %>
<h1>Edit Day</h1>

<%= turbo_frame_tag @day do %>
  <%= render "form", workout: @workout, day: @day %>
<% end %>

app/views/days/new.html.erb
<%= link_to sanitize("&larr; Back to workout"), workout_path(@workout) %>
<h1>New day</h1>

<%= render "form", workout: @workout, day: @day %>

app/views/days/show.html.erb
<%= link_to sanitize("&larr; Back to days"), workout_path(@workout), class: "text-red-700 text-lg hover:text-red-600 mt-2" %>
<div class="flex justify-between my-4 py-3 items-center">
  <h1 class="text-4xl font-bold">
    <%= @day.title %>
  </h1>
  <%= link_to "Add Exercise", new_workout_day_exercise_path(@workout, @day), data: { turbo_frame: dom_id(Exercise.new) },
                class: "bg-red-700 hover:bg-red-600 text-white text-lg font-semibold py-3 px-5 rounded-md" %>
</div>
<%= turbo_frame_tag Exercise.new %>
<%= turbo_frame_tag "exercises" do %>
  <%= render @exercises, workout: @workout, day: @day %>
<% end %>

<div class="text-center pt-3">
  <%= button_to 'Add to history', workout_day_history_days_path(@workout, @day), id: 'submit', class: "bg-red-700 hover:bg-red-600 text-white text-lg font-semibold py-3 px-5 rounded-md" %>
</div>

app/views/days/update.turbo_stream.erb
<%# Step 2: insert the updated date at the correct position %>

  <%= turbo_stream.replace @day do %>
    <%= render @day, workout: @workout %>
  <% end %>


<%# <%= render_turbo_stream_flash_messages %> 