config/routes.rb
Rails.application.routes.draw do
  root 'workouts#index'
  devise_for :users

  resources :workouts do
    resources :days, except: %i[index] do
      resources :exercises, except: %i[index show] do
        resources :exercise_sets, except: %i[index show]
      end
    end

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
  end

  resources :workouts do
    resources :days, except: %i[index] do
      resources :history_days do
        resources :history_exercises do
          resources :history_sets
        end
      end
    end
  end

  resources :history_days do
    resources :history_exercises do
      resources :history_sets
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Built4Life</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%# <body class=" bg-orange-50"> %>
    <nav class="flex justify-between border-b border-gray-300 shadow-lg py-4 px-5 items-center text-gray-800">
      <div class="font-bold text-2xl">
        <%= link_to 'Built4Life', root_path %>
      </div>
      <% if user_signed_in? %>
        <div class="flex font-semibold text-lg items-center gap-2">
          <%= link_to 'History', history_days_path %>
          <%#= current_user.email %>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: "bg-gray-900 hover:bg-gray-700 text-white py-3 px-5 rounded-md ml-2" %>
        </div>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: "bg-gray-900 hover:bg-gray-700 text-white py-3 px-5 rounded-md ml-2" %>
      <% end %>
    </nav>
    <main class="mx-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>